server:
  port: 8081
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.herba.model.entity
spring:
  application:
    name: blog
  datasource:
    url:  jdbc:mysql://107.175.220.10:3306/herba?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wwx232324

