server:
  port: 8081
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.herba.model.entity
spring:
  application:
    name: blog
  datasource:
    url:  jdbc:mysql://118.24.42.37:3306/herba?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    数据库驱动类
#    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: herba
    password: wwx232324
  http:
    multipart:
      max-file-size: 100mb
      max-request-size: 100mb
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis数据库地址
    host: 127.0.0.1
    # Redis数据库密码
    password:
    # Redis数据库端口
    port: 6379
    # Redis数据库超时时间
    timeout: 3000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最大空闲连接
      min-idle: 0
# 后台参数
# 图片保存路径
herba.file.imageFilePath: src/main/resources/uploadImages/
# 文件保存路径
herba.file.filePath: src/main/resources/uploadFiles/
#文件显示Api
herba.file.imageShowApi: http://192.168.50.224:8081/getImage/
#文件下载Api
herba.file.fileDownloadApi: http://192.168.50.224:8081/getFile/
logging:
  level: info
  level.org.herba.model.mapper: debug
  level.org.springframework.security: debug
  file: ../spring-boot.log
security:
  oauth2:
    resource:
      filter-order: 3
  basic:
    enabled: false
