server:
  port: 8081
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.herba.model.entity
spring:
  application:
    name: blog
  datasource:
    url:  jdbc:mysql://107.175.220.10:3306/herba?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    数据库驱动类
#    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: herba
    password: wwx232324
  http:
    multipart:
      max-file-size: 100mb
      max-request-size: 100mb
# 后台参数
# 图片保存路径
herba.file.imageFilePath: src/main/resources/uploadImages/
# 文件保存路径
herba.file.filePath: src/main/resources/uploadFiles/
#文件显示Api
herba.file.imageShowApi: http://192.168.50.224:8081/getImage/
#文件下载Api
herba.file.fileDownloadApi: http://192.168.50.224:8081/getFile/
logging:
  level: info
security:
  basic:
    enabled: false