server:
  port: 8081
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.herba.model.entity
spring:
  application:
    name: blog
  datasource:
    url:  jdbc:mysql://103.73.49.126:3306/herba?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: herba
    password: wwx232324
# 后台参数
# 图片保存路径
imageFilePath: src/main/resources/uploadImages/
# 文件保存路径
filePath: src/main/resources/uploadFiles/
#文件显示Api
imageShowApi: http://localhost:8081/getImage/
#文件下载Api
fileDownloadApi: http://localhost:8081/getFile/